# Generated by Django 3.0.7 on 2020-06-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showvideo', '0004_auto_20200616_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Куча Видео'},
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
